var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = +5.6 - 22;
myBool = true;
myVar = true;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false];
strNumTuple = ['Hello', 3];
var myVoid = null;
var myNull = null;
var myUndefined = undefined;
console.log(myVoid);
